services:
  order-postgres:
    image: postgres:16
    container_name: order-postgres
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password
      POSTGRES_DB: order_lifecycle
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U order_user -d order_lifecycle" ]
      interval: 5s
      timeout: 5s
      retries: 10
